---
- name: Configure Nexus server
  hosts: nexus
  vars:
    ansible_become: true
  roles:
    - role: geerlingguy.java
      vars:
        java_packages:
          - java-1.8.0-openjdk

    - role: ansible-ThoTeam.nexus3-oss
      vars:
        # This is the work directory used by the non-OSS version:
        nexus_data_dir: /opt/sonatype-work
        # For a PoC this is ok, but normally you'd encrypt this:
        nexus_admin_password: Abcd1234!
        nexus_anonymous_access: false
        nexus_config_yum: true
        nexus_repos_yum_hosted:
          - name: yum
        nexus_config_pypi: true
        nexus_repos_pypi_hosted:
          - name: pypi
        nexus_roles:
          - id: upload-yum
            name: upload-yum
            description: Uploader to yum repository
            privileges:
              - nx-repository-view-yum-yum-add
              - nx-repository-view-yum-yum-edit
          - id: upload-pypi
            name: upload-pypi
            description: Uploader to pypi repository
            privileges:
              - nx-repository-view-pypi-pypi-add
              - nx-repository-view-pypi-pypi-edit
          - id: download-yum
            name: download-yum
            description: Downloader of yum repository
            privileges:
              - nx-repository-view-yum-yum-read
          - id: download-pypi
            name: download-pypi
            description: Downloader of pypi repository
            privileges:
              - nx-repository-view-pypi-pypi-read
        nexus_local_users:
          - username: upload-yum
            password: Abcd1234!
            first_name: upload
            last_name: yum
            email: nobody@example.com
            roles:
              - upload-yum
            state: present
          - username: upload-pypi
            password: Abcd1234!
            first_name: upload
            last_name: pypi
            email: nobody@example.com
            roles:
              - upload-pypi
            state: present
          - username: download-yum
            password: Abcd1234!
            first_name: download
            last_name: yum
            email: nobody@example.com
            roles:
              - download-yum
            state: present
          - username: download-pypi
            password: Abcd1234!
            first_name: download
            last_name: pypi
            email: nobody@example.com
            roles:
              - download-pypi
            state: present

  tasks:
    - name: Open up port 8081 from the outside
      ansible.posix.firewalld:
        port: 8081/tcp
        permanent: true
        state: enabled
        immediate: true
      tags: firewall

    - name: Check if Nexus Repository Manager is accessible (this can take a couple of minutes)
      ansible.builtin.uri:
        url: http://{{ ansible_host }}:8081
        return_content: false
      delegate_to: localhost
      register: nexus_response
      until: nexus_response.status == 200
      retries: 20
      delay: 5
      check_mode: false
      tags: health_check
