---
- name: Install poc-package from Nexus
  hosts: nexus
  vars:
    ansible_become: true
    poc_package_version: "0.1"
    nexus_server: "{{ ansible_host }}"
  gather_facts: false
  tasks:
    - name: Configure yum Nexus repo
      ansible.builtin.yum_repository:
        name: nexus
        description: Nexus YUM repo
        baseurl: http://192.168.14.34:8081/repository/yum/
        username: download-yum
        password: Abcd1234!

    - name: Copy GPG public key
      ansible.builtin.copy:
        src: /home/vagrant/.gnupg/ansible.pub
        dest: /root/ansible.pub
        mode: "0644"

    - name: Import GPG public key in rpm
      ansible.builtin.rpm_key:
        key: /root/ansible.pub

    - name: Install poc-package
      ansible.builtin.yum:
        name: poc-package
        update_cache: true
        state: present

    - name: Read hello.txt
      ansible.builtin.slurp:
        src: /opt/poc/hello.txt
      register: slurp_result

    - name: Assert hello.txt contains the right content
      ansible.builtin.assert:
        that: slurp_result.content | b64decode == 'hello 0.1'

    - name: Read world.txt
      ansible.builtin.slurp:
        src: /opt/poc/world.txt
      register: slurp_result

    - name: Assert world.txt contains the right content
      ansible.builtin.assert:
        that: slurp_result.content | b64decode == 'world 0.1'
